server:
  AppVersion: 1.0.0
  Port: :5000
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: secretkey
  CookieName: jwt-token
  ReadTimeout: 10
  WriteTimeout: 10
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info

postgres:
  PostgresqlHost: postgres_db
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDbname: test_db
  PostgresqlSslmode: false
  PgDriver: pgx

redis:
  RedisAddr: redis:6379
  RedisPassword: ""
  RedisDb: "0"
  RedisDefaultdb: "0"
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0
  KeyPrefix: "health:"

kafka:
  Addr: kafka:9092
  ChatTopic: chat-messages
  MessageTopic: chat-notifications
  GroupID: chat-group
  RetentionTime: 86400 # 24 hours in seconds
  MaxWait: 3 # seconds
  BatchSize: 100
  BatchTimeout: 1 # seconds

chat:
  PingInterval: 30 # seconds
  PongWait: 60 # seconds
  WriteWait: 10 # seconds
  MaxMessageSize: 4096 # bytes
  MessageQueueSize: 256
  UserOnlineTTL: 600 # 10 minutes in seconds

metrics:
  url: 0.0.0.0:7070
  service: api

cookie:
  Name: jwt-token
  MaxAge: 86400
  Secure: false
  HttpOnly: true

session:
  Name: session-id
  Prefix: api-session
  Expire: 3600

jaeger:
  Host: localhost:6831
  ServiceName: REST_API
  LogSpans: true
