basePath: /api/v1
definitions:
  models.User:
    properties:
      about:
        type: string
      address:
        type: string
      avatar:
        type: string
      birthday:
        type: string
      city:
        type: string
      country:
        type: string
      createdAt:
        type: string
      email:
        type: string
      firstName:
        type: string
      gender:
        type: string
      lastName:
        type: string
      loginDate:
        type: string
      password:
        type: string
      phoneNumber:
        type: string
      postcode:
        type: integer
      role:
        type: string
      updatedAt:
        type: string
      userID:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a Go API with Swagger.
  title: Go example REST API
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: register new user, returns user and token
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
      summary: Register new user
      tags:
      - Auth
swagger: "2.0"
