basePath: /api/v1
definitions:
  models.Expertiese:
    properties:
      category:
        type: string
      consultant_id:
        type: integer
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      identity_proof:
        type: string
      updated_at:
        type: string
      video_url:
        type: string
    required:
    - category
    - consultant_id
    type: object
  models.Interest:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      image_url:
        type: string
      name:
        type: string
      updated_at:
        type: string
    type: object
  models.User:
    properties:
      active:
        type: boolean
      city:
        type: string
      country:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      expertiese:
        $ref: '#/definitions/models.Expertiese'
      id:
        type: integer
      interests:
        items:
          $ref: '#/definitions/models.Interest'
        type: array
      name:
        maxLength: 100
        minLength: 2
        type: string
      password:
        minLength: 6
        type: string
      phone:
        type: string
      role:
        enum:
        - customer
        - consultant
        type: string
      updated_at:
        type: string
    required:
    - email
    - name
    - password
    - role
    type: object
host: localhost:5000
info:
  contact: {}
  description: API cho hệ thống Health Backend
  title: Health Backend API
  version: "1.0"
paths:
  /auth/register:
    post:
      consumes:
      - application/json
      description: register new user, returns user and token
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
      summary: Register new user
      tags:
      - Auth
swagger: "2.0"
